### ISSUE TITLE
Error when opening XPMenu

### ISSUE THREAD

**Issue by filipovskis** [XenPare/XPGUI#1]
[gmonopoly] lua/vgui/dscrollpanel.lua:135: attempt to call method 'PerformLayoutInternal' (a nil value)
  1. PerformLayout - lua/vgui/dscrollpanel.lua:135
   2. PerformLayout - addons/gmonopoly/lua/gmonopoly/libraries/xpgui/vgui/menu.lua:203
    3. unknown - addons/gmonopoly/lua/gmonopoly/libraries/xpgui/vgui/scrollpanel.lua:15 (x72)

![image](https://user-images.githubusercontent.com/48033052/98446783-a7a5c700-2128-11eb-8a01-08c85aabcb28.png)

**Comment by filipovskis** [comment]
Check pull request, there's a fix

**Comment by cresterienvogel** [comment]
> Check pull request, there's a fix

done, thanks for the contribution
